name: authenticator_app
description: "Mobile application similar to Google Authenticator that generates one-time codes for two-factor authentication (2FA)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^9.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  flutter_svg: ^2.0.17
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_button: ^2.0.6
  flutter_secure_storage: ^9.2.4
  circle_nav_bar: ^2.2.0
  flutter_floating_bottom_bar: ^1.2.1+1
  path_provider: ^2.1.5
  totp: ^0.1.0
  equatable: ^2.0.7
  hotp: ^0.1.0
  cloud_firestore: ^5.6.6
  connectivity_plus: ^5.0.1
  local_auth: ^2.3.0

# DEV
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  generate: true

  assets:
    - lib/l10n/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf

  uses-material-design: true


flutter_intl:
  enabled: true
  main_locale: uk
  synthetic-package: false